### ISSUE TITLE
demo does not work on Chrome and Safari

### ISSUE THREAD

**Issue by Hongbo-Miao** [unlayer/react-email-editor#10]
I tried the demo
http://react-email-editor-demo.netlify.com/

It works in Firefox, but does not work in Chrome and Safari. It only shows a top bar.
Chrome 65.0.3325.31
Safari 11.0.3

![image](https://user-images.githubusercontent.com/3375461/35830150-2230873a-0a7a-11e8-8283-986f3723e227.png)

**Comment by bertho-zero** [comment]
It works in Chrome 64.0.3282.119 on Ubuntu

**Comment by adeelraza** [comment]
Just tested, works fine on both. @Hongbo-Miao do you see any errors in console?

**Comment by Hongbo-Miao** [comment]
Chrome
![image](https://user-images.githubusercontent.com/3375461/35901396-40d5bd74-0b8b-11e8-99f4-a8fc3dcca245.png)

Safari
![image](https://user-images.githubusercontent.com/3375461/35901415-50f1a7b8-0b8b-11e8-918b-b756b665e379.png)

**Comment by adeelraza** [comment]
@Hongbo-Miao Everything looks good with the SSL certificate: https://www.sslshopper.com/ssl-checker.html#hostname=https://editor.unlayer.com/embed.js

It looks like something is up with your local connection?

**Comment by Hongbo-Miao** [comment]
I don’t know.. But I does work in my Firefox.
