### ISSUE TITLE
table instead of html

### ISSUE THREAD

**Issue by vmiracle13** [unlayer/react-email-editor#102]
Hello!

Could you please specify how it is possible to get only table tag with its content instead of the whole html? We need to add more information during generating email html. But there is no option to get only tag table>... tag /table> part. Also regexp does not find tag table> part in html.

**Comment by adeelraza** [comment]
@vmiracle13 you can use the chunk parameters: https://docs.unlayer.com/docs/export-html#section-chunk-parameters
