### ISSUE TITLE
React component does not have registerTool

### ISSUE THREAD

**Issue by rexkenley** [unlayer/react-email-editor#105]
Hi

I tried to create some custom tools and noticed that the react component object does not have registerTools. 

Will this be added to the component?

**Comment by adeelraza** [comment]
`registerTool` is only available inside the `customJS`.  You can pass `customJS` in the `options` prop to the React component. Check the docs here: https://docs.unlayer.com/docs/custom-js-css#section-custom-javascript

```
<EmailEditor
    options={{ customJS: "console.log('I am custom JS!', unlayer.registerTool);" }}
/>
```

**Comment by rexkenley** [comment]
So this is not available, since customJS is a premium feature that requires purchase. Is that correct?

**Comment by adeelraza** [comment]
@rexkenley the free plan allows 1 custom tool, but not the JavaScript one. You can create it using our dashboard GUI. And then pass in the `projectId` to options.

**Comment by rexkenley** [comment]
Thank you.
