### ISSUE TITLE
using EmailEditor inside of FunctionalComponent does not work correctly

### ISSUE THREAD

**Issue by dohomi** [unlayer/react-email-editor#108]
Hello,

I tried to use EmailEditor inside a FunctionalComponent. I re-open the editor and after the first initial load the data is lost and the reference is not there any longer.

Does anyone use this component with a FunctionalComponent?

Thanks!

**Comment by kwayebopp** [comment]
I had some success after using the vanilla JS implementation of react-email-editor provided by Unlayer [here](https://github.com/unlayer/examples/blob/master/javascript/basic/src/index.html). Just add the embed script to your `index.html` file and you can do something like this:

```
const EmailEditor = () => {
  const { unlayer } = window;

  const initializeUnlayer = () =>
    unlayer.init({
      id: "unlayer"
    });

  useEffect(() => {
    initializeUnlayer();
  }, []);

   return <div id="unlayer" />;
}

```

This should be enough for a minimal setup. Handling loading and saving can be done by using the functions like `unlayer.loadDesign` and `unlayer.exportHtml`, which behave identically to the ones that would be available in the ref as used in the `react-email-editor` README.

Hope this helps.

**Comment by dohomi** [comment]
@kwayebopp I also did now the bare JS integration, this react wrapper seems to not reliably work with FunctionalComponents
