### ISSUE TITLE
Does this work for building landing pages or only email?

### ISSUE THREAD

**Issue by joshbedo** [unlayer/react-email-editor#116]
Does this work for building landing pages or only email?

**Comment by joshbedo** [comment]
Somebody please tell me yes :D

**Comment by joshbedo** [comment]
@lidrissi does the thumbs up mean yes? lol or are you curious too.

**Comment by adeelraza** [comment]
@joshbedo yes we do support landing pages as well, but you may have to fork this package or use our JavaScript SDK directly. Look for `displayMode` https://docs.unlayer.com/docs

**Comment by joshbedo** [comment]
Great! thank you!
