### ISSUE TITLE
1 mb upload limit even if it to anther server

### ISSUE THREAD

**Issue by NetanelRotem** [unlayer/react-email-editor#12]
Hey, Is there any way to cancel the limitaion on uploading an image, to another storge?
Now, If I try to upload an  image to my storge it gives me this error message : "There was an error uploading your image. Make sure it's a valid image file with size under 1 MB."

**Comment by umairsiddique** [comment]
@NetanelRotem the upload limit is 2 MB for free projects and 10 MB for paid projects.

**Comment by HyperMaxime** [comment]
It appears that 2mb is indeed the limit for free projects (successfully uploaded a 1.9mb file, but not a 2.1mb file). However, the editor is communicating a 1MB limit, which is a bit deceiving for the user:

![image](https://user-images.githubusercontent.com/24253436/41408245-eacace3a-6fc9-11e8-9232-63f5ff7a9ac9.png)

**Comment by adeelraza** [comment]
@HyperMaxime thank you, this has been fixed.

**Comment by GimpMaster** [comment]
This bug seems to have gotten back into the main code. It still lists a 1MB file upload. Not 2 MB.

**Comment by continue47** [comment]
Is the 2MB limit when uploading to our own server by design or a bug? We are hosting the images ourselves so it shouldn't matter, right? Anyone have any info on this?

**Comment by RFTaurus** [comment]
same here, I upload to our own server but I can't find to tweak the limit size of it to make it bigger, our server accept file max 4Mb
