### ISSUE TITLE
email-editor not working in IE 11.

### ISSUE THREAD

**Issue by VenkateshSadhasivam** [unlayer/react-email-editor#124]
Hi,

Email-editor has worked IE11 in old version but it is not working higher version. I am changed new version into old version but it is also not working.Could you help me for this issue?

**List of I am faced issues**

- I am added content in editor but editor not allowing content drag & drop in IE11 latest browser and also image added below.

<img width="960" alt="Captureuiu" src="https://user-images.githubusercontent.com/39042295/82526408-956fa680-9b51-11ea-9637-a8e2077ce830.PNG">

Now email editor IE11 Browser is there Support or not .

**Comment by adeelraza** [comment]
@VenkateshSadhasivam can you check this now?

**Comment by VenkateshSadhasivam** [comment]
@adeelraza Thanks, Now it is working fine.
