### ISSUE TITLE
Misleading npm package name

### ISSUE THREAD

**Issue by fedulovivan** [unlayer/react-email-editor#128]
You editor is a commercial product which is actually not a react editor. 
Shouldn't this package been called as unlayer-email-editor?
Leave this npm name for project which deserves it.

**Comment by adeelraza** [comment]
@fedulovivan this is a `wrapper` component for the Unlayer editor as clearly mentioned in the description. This is not commercial, all functionality listed in the description is available completely for free, and forever.

**Comment by fedulovivan** [comment]
Be honest, current packackage name, is kind of squatting.  Most people will consider "okay, looks like an email editor implemented on react". The truth is different. Check [the policy](https://www.npmjs.com/policies/disputes).
