### ISSUE TITLE
Where should I add dropdown options?

### ISSUE THREAD

**Issue by Skavengerr** [unlayer/react-email-editor#132]
Like this not working

<img width="720" alt="Снимок экрана 2020-07-02 в 15 16 19" src="https://user-images.githubusercontent.com/41162650/86357791-0b018300-bc77-11ea-8a97-7bf354d68548.png">

**Comment by Skavengerr** [comment]
`var int = 1`

**Comment by adeelraza** [comment]
@Skavengerr you need to change `department` to `products`
