### ISSUE TITLE
 Could not find a valid element for given id or className.

### ISSUE THREAD

**Issue by aahadaazar** [unlayer/react-email-editor#133]
Hello. I am trying to embed unlayer editor in my fresh react app. But it is giving the following error:
![Capture](https://user-images.githubusercontent.com/35993121/86349936-53bb3b00-bc7b-11ea-8fd0-43c1db1bd978.PNG)

my code snippet is:
![Capture](https://user-images.githubusercontent.com/35993121/86350002-70f00980-bc7b-11ea-9a2e-6d91311c98a5.PNG)
![Capture](https://user-images.githubusercontent.com/35993121/86350036-7ea58f00-bc7b-11ea-99e7-3ca44e42f719.PNG)

**Comment by Abhikumar98** [comment]
how did you solve this ?

**Comment by aahadaazar** [comment]
@Abhikumar98 I actually downgraded to 1.0.0 and wrapped the Email Editor in a div with classname 'APP'.
Tried doing it with latest version, didnt work

**Comment by ivrylobs** [comment]
Every time browser request the page the server will always send all bundles and builds with new element-id even refresh the editor page in client still have same editor id but server is difference id
