### ISSUE TITLE
How to add API-KEY in react-email-editor

### ISSUE THREAD

**Issue by manthan-sf** [unlayer/react-email-editor#135]
How to add API-KEY in react-email-editor  , so my account is linked with editor

**Comment by manthan-sf** [comment]
I am using react-email-editor React  Compononet

**Comment by adeelraza** [comment]
@manthan-sf you can pass the `projectId` in the `options` prop. Based on your project domains, we will automatically fetch the API key.

**Comment by immutablegoblin** [comment]
How do I do this now the projectId props has been deprecated, please?

**Comment by ahsansher** [comment]
It has moved to options prop:
`options={{
          projectId: 12345,
          templateId: 12345,
 }}`
