### ISSUE TITLE
Are subtemplates possible?

### ISSUE THREAD

**Issue by DigitalFlow** [unlayer/react-email-editor#141]
Hi there,

Thanks for this tool, it is providing great value in the areas where we use it.

I have one question:
We use some snippets as MergeTags. Now some users mentioned the need to use HTML in there too.
Of course this works without any additions, but you have to write the HTML inside the snippets by hand.

We would be able to use the react-email-editor for easily defining HTML snippets as well, but then when inserting these, we would insert a full html document with <html> tag and all style sheets into our "parent" template.

Do you see a use case, where you might allow to export the pure content of the designer, without HTML root and styling info, or should we rather handle this on our own and strap everything?

Thanks for your help & Kind Regards,
Florian

**Comment by sarpkayature** [comment]
After 3 years im going to write you as you not received anything. There is user blocks or custom blocks. Ofcourse its in paid plan.

**Comment by DigitalFlow** [comment]
Hi @sarpkayature,

thanks for your response, I'll close this issue :)

Kind regards,
Florian
