### ISSUE TITLE
Could not find a valid element for given id or className

### ISSUE THREAD

**Issue by jayanthbondi** [unlayer/react-email-editor#147]
Hello,
I'm using a react version of 16.13.1, I got the above issue while rendering EmailEditor of 1.1.1 version.
Can someone help me.

Thanks in advance.

**Comment by lidrissi** [comment]
try with `    "react-email-editor": "^0.9.5",
`

**Comment by adeelraza** [comment]
@jayanthbondi what `react` and `react-dom` version are you on?

**Comment by adeelraza** [comment]
This issue has been resolved. Can you update to the latest version of `react-email-editor`?

**Comment by jayanthbondi** [comment]
Thankyou @adeelraza and @lidrissi 
It worked fine when I update my email-editor version to 1.2.0 from 1.1.1.
