### ISSUE TITLE
How will I be able to make the editor height, fit to my window height?

### ISSUE THREAD

**Issue by jayanthbondi** [unlayer/react-email-editor#159]
![image](https://user-images.githubusercontent.com/35721161/99413031-59a87480-291b-11eb-8b70-1d66a2c753bb.png)

**Comment by jayanthbondi** [comment]
Attaching the sandbox link
https://codesandbox.io/s/amazing-northcutt-1g66z

**Comment by adeelraza** [comment]
@jayanthbondi the editor is designed to take 100% of it's parent width and height. Please make sure the container height is set to what you want.

**Comment by jayanthbondi** [comment]
Hi @adeelraza can you try to edit in the code pen link which I shared and let me know?
I'm not understanding what actually I am missing.

**Comment by adeelraza** [comment]
@jayanthbondi your html, body and root div should be 100% height or set to a height you want the editor to be.

**Comment by jayanthbondi** [comment]
Thanks @adeelraza it worked for me.
I have given a height of 100vh to the editor.
