### ISSUE TITLE
Text-editing capabilities are broken for Brave browser

### ISSUE THREAD

**Issue by finaldave** [unlayer/react-email-editor#172]
It looks like the following are broken for the Brave browser (it's Chromium based like Chrome so I'm surprised there are issues that don't pop up in Chrome):

1. Editing a text field placed on a template
2. Editing a header placed on a template

Clicking the text field or header to alter its text gives the following error:

`editor.js:101 TypeError: Cannot read property 'getItem' of null
    at contentEditor.chunk.js:1
    at contentEditor.chunk.js:1
    at Object.<anonymous> (contentEditor.chunk.js:1)
    at Object.1406 (contentEditor.chunk.js:1)
    at i (editor.js:1)
    at Module.1232 (contentEditor.chunk.js:1)
    at i (editor.js:1)`

To reproduce:

1. Install and open Brave via https://brave.com/download/
2. Navigate to https://react-email-editor-demo.netlify.app/
3. Add a text field to the template
4. Click on the text field

Expected result:
The text field is editable like it is in Chrome

Actual result:
The entire editor turns white and the above error is reported in the console

**Comment by alina-unlayer** [comment]
We are looking into this issue. As of now, if you turn off the Brave Shields for your web application, then the text-editing capabilities work fine.

**Comment by damiandzwigaj** [comment]
Same here, im seeing more and more people moving to Brave(currently best option for osx) so i guess thats a big issues

**Comment by webpolis** [comment]
Same

**Comment by alina-unlayer** [comment]
Your feedback has been recorded and you can track the progress from [here](https://unlayer.canny.io/bug-reports/p/text-editing-capabilities-are-broken-for-brave-browser).

**Comment by kulesa** [comment]
This can be fixed by disabling Brave 'shields' for the editor page - click on the Brave icon next to the browser address bar and turn the shields switch off.

**Comment by adeelraza** [comment]
This issue has been resolved.
