### ISSUE TITLE
react 17 support 

### ISSUE THREAD

**Issue by yoosuf** [unlayer/react-email-editor#174]
➜  tetsproject git:(master) npm install react-email-editor --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: o2o-mailer@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x" from react-email-editor@1.2.0
npm ERR! node_modules/react-email-editor
npm ERR!   react-email-editor@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/yoosuf/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yoosuf/.npm/_logs/2021-02-24T16_17_01_203Z-debug.log

**Comment by gaurav3017** [comment]
Expecting React 17 support soon. For the mean time`npm install react-email-editor --force` worked for me.
