### ISSUE TITLE
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

### ISSUE THREAD

**Issue by sorin21** [unlayer/react-email-editor#18]
Hello,

I opened the email template this morning and I saw in the browser console this error:

`The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'`

This is a [screenshot](http://prntscr.com/jme68d) to see clearly what is happening.

Can you please tell me what is going on? Are you making updates to unlayer now and that's why the error show up?

**Comment by adeelraza** [comment]
@sorin21 I cannot reproduce this error. Are you seeing this in local dev mode only or also in production? Please check the live demo http://react-email-editor-demo.netlify.com/ for production mode.

**Comment by sorin21** [comment]
Hello my friend, adeelraza,
I don't know what you did or those guys, for the third part plugins/scripts that you use on this email, but now I don't see the error anymore. I didn't put it in the production yet, because I got this error last week on dev and I stopped. 

I checked the error on google and I saw that I can't modify anything because the script were from the error is generated is not locally, in the unlayer email folder, that I installed.

Thank you very much for answer. You can close the issue :).
