### ISSUE TITLE
"Upload image" Button missing when trying to use custom Media Library

### ISSUE THREAD

**Issue by pr0gr8mm3r** [unlayer/react-email-editor#184]
# Setup
1. Using free version without project id
2. calling `emailEditorRef.current?.editor?.registerCallback('selectImage', onSelectImageHandler);` to make a custom function handle media selection

Now there is, as expected, no drag and drop area, but there is also no button to open the library. Notice how in the following screenshot, only the URL field is visible:
![image](https://user-images.githubusercontent.com/37022952/113205568-ba06d580-926e-11eb-8fb7-dbdbb070a540.png)

Contrast that to the following screenshot form the [examples](https://examples.unlayer.com/media/custom-media-library):
![image](https://user-images.githubusercontent.com/37022952/113205942-1e299980-926f-11eb-8a54-b574a72b5fbb.png)

Is this feature only available for paid plans? If yes, it would be great if it said so in the docs.

**Comment by damiandzwigaj** [comment]
looks like its paid feature, your code works for me

**Comment by pr0gr8mm3r** [comment]
Thanks for your reply. I'm going to leave this issue open so a notice about that can be added to the docs.

**Comment by adeelraza** [comment]
@pr0gr8mm3r "Upload Image" should be visible. It was probably related to this: https://roadmap.unlayer.com/bug-reports/p/choose-image-button-disappeared-if-any-register-callback-is-used-in-all-react-an

**Comment by pr0gr8mm3r** [comment]
It's working for me, thanks!
