### ISSUE TITLE
Row/column background issue

### ISSUE THREAD

**Issue by dkrasov** [unlayer/react-email-editor#19]
Hey guys,

I've found a very strange bug in your plugin.

If you add a row, but do not specify anything for it at all, the generated design will be broken. It means, that if you try to load this design, plugin will work BUT if you will try to click on that new row - plugin will crash.

Here is the screenshot of console and errors I've got:
https://monosnap.com/file/NoHzuRxiaWYZ4oghgU7IQjurNkgj5y

While debugging and trying to find the real issue, I've made a conclusion, that you are trying to detect the background color's scheme (RGB, HEX etc.) and it fails if you do not specify row (or column) background at all after adding new row, because `backgroundColor` and `columnsBackgroundColor` values are `null`.

Looking forward for the fix,
Dmytro.

**Comment by adeelraza** [comment]
@dkrasov we have fixed this issue. Can you clear your cache (or load the editor in incognito mode) and see if it works for you now?

**Comment by dkrasov** [comment]
@adeelraza seems to be working! 👍
