### ISSUE TITLE
is setMergeTags() available for the EmailEditor react component?

### ISSUE THREAD

**Issue by stroypet** [unlayer/react-email-editor#20]
Hi guys,

Likely a noob question, but can I setMergeTags() onLoad if I am using react-email-editor?

My emailEditor div:

`            <div>
              <EmailEditor
              onLoad={this.onLoad} 
              ref={editor => this.editor = editor}
              />
            </div>
`

My onLoad function:

`  onLoad = () => {
    this.editor.loadDesign(this.state.designJson);
    this.editor.setMergeTags([
      {name: "First Name", value: "{{first_name}}"},
      {name: "Last Name", value: "{{last_name}}"}
    ]);
  }
`

Says setMergeTags is not a function.

Thanks in advance for your help.

**Comment by adeelraza** [comment]
@stroypet added support for setMergeTags in 0.8.1. Please try now.

**Comment by stroypet** [comment]
Awesome! Thanks Adeel.
