### ISSUE TITLE
Unable to change styles (container padding) in mobile configuration

### ISSUE THREAD

**Issue by shaynathompson95** [unlayer/react-email-editor#203]
The changes made to the mobile configuration for blocks are not being displayed as expected. Initially, I thought it was just an issue when trying to set a different container padding for mobile; however, it seems that no mobile changes are being reflected. Below I have attached the json which shows 72px for the desktop padding and also the override property for mobile which should be set to 27px. I've also verified that the expected mobile padding (27px) can be seen in exportHtml function. However, in the editor's mobile configuration it is always set to 72px

![image](https://user-images.githubusercontent.com/86655437/123772390-1a3c0080-d8cc-11eb-863c-235e27d0abbc.png)

![image](https://user-images.githubusercontent.com/86655437/123773532-047b0b00-d8cd-11eb-869d-b5a765aa8417.png)

**Comment by SchmidtClaudia** [comment]
That also happens to normal email templates. Any hint how to fix this?
