### ISSUE TITLE
registerCallback not made available

### ISSUE THREAD

**Issue by HyperMaxime** [unlayer/react-email-editor#21]
When setting up [custom file storage](https://docs.unlayer.com/file-storage/) one needs to register a callback, however the react wrapper does not expose this method, unlike others (addEventListener, loadDesign, ...).

It seems to be just a matter of adding:

```
registerCallback = (type, callback) => {
    unlayer.registerCallback(type, callback)
}
```

**Comment by umairsiddique** [comment]
@HyperMaxime kindly upgrade to 0.8.2.

**Comment by JoezerSmaniotto** [comment]
registerCallback needs to be called inside the onReady function:

exemplo:
` const onReady = () => {
    emailEditorRef.current.editor.registerCallback('image', function(file, done) {
     
      let files = file.attachments[0]
      let reader  = new FileReader();
      let imageBase64;
  
      reader.onloadend = function () {
        imageBase64 = reader.result;
        console.log("64 =>", imageBase64)
      }
    
      if (file) {
        reader.readAsDataURL(files);
      }

  };`

remembering that onReady must be inside the EmailEditor component as well as the other props you need.

`<EmailEditor ref={emailEditorRef} onLoad={onLoad} onReady={onReady} saveDesign={saveDesign} options={{locale: 'pt-BR'}}  />`

**Comment by Dharshini012003** [comment]
hello, I just want to know custom file storage available in free tier of unlayer also

**Comment by BharathSubu** [comment]
not it is not available in free tier
