### ISSUE TITLE
Peer dependency to react 17

### ISSUE THREAD

**Issue by pkvpraveen** [unlayer/react-email-editor#214]
Need to upgrade peer dependency to support react 17. https://reactjs.org/blog/2020/10/20/react-v17.html

**Comment by cesargdm** [comment]
Getting errors while trying to install with `npm install`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: web-app@1.4.21
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x" from react-email-editor@1.5.0
npm ERR! node_modules/react-email-editor
npm ERR!   react-email-editor@"1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See <...>/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     <...>/.npm/_logs/2021-12-30T01_26_53_000Z-debug.log
```

**Comment by KennethSylar** [comment]
hi, is there an update to support react 17 for this package ?

**Comment by sonnguyent2** [comment]
@ayushmxn @umairsiddique I saw the source code already add support for React 17 but the npm package (1.5.0) is not republish with new code so the issue still happen. Could you please publish the package with latest code ?

**Comment by ayushmxn** [comment]
@sonnguyent2 you can use this package along with React 17. I didn't encounter any breaking changes. Whenever you install dependencies, it'll just show a peer dependency warning.

**Comment by monomy001** [comment]
nope.. not true.. 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tm-dashboard@2.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x" from react-email-editor@1.5.0
npm ERR! node_modules/react-email-editor
npm ERR!   react-email-editor@"*" from the root project

**Comment by lucasbesen** [comment]
Support to React 17 is now live
