### ISSUE TITLE
lock different blocks

### ISSUE THREAD

**Issue by delamux** [unlayer/react-email-editor#217]
### Is in the feature list that the editor wouldn't be able to modify some blocks by configuration?

In our case we would like that the customer doesn't have access to modify some structure parts of the editor. We wouldn't like that they can slide images or move blocks. Just edit content like edit text or replace images

- Blocked modules
    - blocks
    - menus
- NOT Blocked modules
    - text

In code would be nice something like this:

```javascript
unlayer.init({
  tools: {
    blocks: {
      blocked: true
    },
    menu: {
      blocked: true
    },
   image: {
      enabled: false
    }
  }
});

```

**Comment by delamux** [comment]
What I needed I found here

![image](https://user-images.githubusercontent.com/14236919/140822943-02b05784-7395-41f7-bc2f-a7c621d071ea.png)

**Comment by sundar8521** [comment]
@delamux I have a similar use case. could you help me to find these configuration in unlayer editor?
