### ISSUE TITLE
Support Right-to-left languages

### ISSUE THREAD

**Issue by DigitalFlow** [unlayer/react-email-editor#233]
Hi everyone,

for sending e-Mails to recipients in languages that are written from right to left such as Arabic or Hebrew, we would probably need to set the `dir` attribute of the HTML element to `rtl`:

```HTML
<html dir="rtl" lang="ar">
...
</html>
```
Source: https://www.w3.org/International/questions/qa-html-dir 

It seems this is not possible right now. Could we add a new property to the `body` tab of the editor? Could be a drop down where we can choose between `rtl` and `ltr`.

Kind regards,
Florian

**Comment by YitzchakMeltz** [comment]
Same issue

**Comment by hadifarnoud** [comment]
use this instead
https://github.com/zalify/easy-email-editor

**Comment by brunolemos** [comment]
You can set `textDirection: 'rtl'` in the init config options. 

See docs: https://docs.unlayer.com/docs/getting-started#configuration-options

**Comment by hadifarnoud** [comment]
can I use RTL for individual blocks only?
