### ISSUE TITLE
Set the default values of the editor on load

### ISSUE THREAD

**Issue by anargiris** [unlayer/react-email-editor#238]
I want to set the default background color to white and the content width to 100% but haven't found a good way to do this yet. I am using React v17.0.2

The following code doesn't seem to work: 

```
unlayer.setBodyValues({
  backgroundColor: "#e7e7e7",
  contentWidth: "500px", // or percent "50%"
  fontFamily: {
    label: "Helvetica",
    value: "'Helvetica Neue', Helvetica, Arial, sans-serif"
  },
  preheaderText: "Hello World"
});
```

This code seems to work for 1 second, then the styles are reset to the email editor's defaults: 

```
emailEditorRef.current.editor.loadBlank({
          backgroundColor: "#fff",
        });
```

Has anyone found a solution to this?

**Comment by nkrmr** [comment]
I have the same issue it is not possible to set a default backgroundColor.  
The loadBlank doesn't work

**Comment by ryan-xin** [comment]
Found a way to use `Events`
`            unlayerEditor.loadBlank({
              backgroundColor: "#f5f5f5",
            });
            unlayerEditor.addEventListener("design:loaded", () => {
              unlayerEditor.setBodyValues({
                backgroundColor: "#f5f5f5",
                contentWidth: "100%",
              });
            });`

**Comment by lucasbesen** [comment]
To make it work correctly you can use `onReady` event.

```js
const onReady = () => {
  emailEditorRef.current.editor.setBodyValues({
    backgroundColor: '#f5f5f5',
    contentWidth: '500px', // or percent "50%"
    fontFamily: {
      label: 'Helvetica',
      value: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    },
    preheaderText: 'Hello World',
  });
};

<EmailEditor ref={emailEditorRef} onLoad={onLoad} onReady={onReady} />
```

**Comment by brunolemos** [comment]
> @anargiris: This code seems to work for 1 second, then the styles are reset to the email editor's defaults:
> 
> ```js
> emailEditorRef.current.editor.loadBlank({
 >  backgroundColor: "#fff",
> });
> ```

> @nkrmr: I have the same issue it is not possible to set a default backgroundColor.
The loadBlank doesn't work

The `loadBlank(bodyValues)` issue has been fixed.

About `setBodyValues`, the current recommendation is to call it either on `design:loaded` or `editor:ready`.
Thanks!

**Comment by brunolemos** [comment]
As of `v1.2.160` you can call `.setBodyValues` normally right after `.loadDesign` without the need of using an event.

**Comment by babycourageous** [comment]
Sorry to ping an old issue - but I'm not able to call `setBodyValues` on my editor

It appears it doesn't exist in the type definitions so get typescript error trying to access a function that doesn't exist.

![image](https://github.com/unlayer/react-email-editor/assets/14936212/20b73b0f-61ac-4246-a78d-7e649c34067c)

You can see in the screenshot it isn't listed along with the other editor options/functions.
I'm currently using `loadBlank` as a workaround but would love to access `setBodyValues`. 


Happy to start a new one if you feel it's necessary
Thanks!

**Comment by brunolemos** [comment]
@babycourageous please make sure you are using the latest version, which is currently `1.7.9`:

<img width="833" alt="image" src="https://github.com/unlayer/react-email-editor/assets/619186/1994d1ab-0259-40b1-9871-131c8c0bb9dc">

**Comment by babycourageous** [comment]
AH! 🤦 how did i miss that. I read my 1.7.8 as 1.7.9
oh - you sneaky little number. Thanks so much!

**Comment by ankit-plivo** [comment]
How can i set the title tag in the exported html . I am using like this   
```
editorRef?.current?.editor.setBodyValues({
      preheaderText: 'hello world'
    })
```

version 1.7.9
