### ISSUE TITLE
Horizontal scroll in sidebar

### ISSUE THREAD

**Issue by HyperMaxime** [unlayer/react-email-editor#24]
The editor sidebar for some reason has a horizontal scroll that is unexpected.
Illustrative GIF below: 

![react-email-editor-horizontal-scroll](https://user-images.githubusercontent.com/24253436/41247618-66db63ca-6da6-11e8-9b8b-e41177468812.gif)

**Comment by adeelraza** [comment]
@HyperMaxime looking at the tab icons, it looks like **unlayer.init** was called multiple times which may have caused this. Can you confirm?

**Comment by HyperMaxime** [comment]
@adeelraza not sure about that, but I can tell you that this behaviour also happens in the [demo on unlayer.com](https://unlayer.com/demo/):

![unlayer-horizontal-scroll-public-demo](https://user-images.githubusercontent.com/24253436/41402555-77693a30-6fba-11e8-9692-163c9d5e646c.gif)

**Comment by adeelraza** [comment]
@HyperMaxime this issue has been resolved. Please check in Incognito

**Comment by HyperMaxime** [comment]
@adeelraza confirmed. Great work, thank you!
