### ISSUE TITLE
Property 'editor' does not exist on type 'never'.

### ISSUE THREAD

**Issue by MaxMcNally** [unlayer/react-email-editor#263]
When using Typescript, the react example gives the error - `Property 'editor' does not exist on type 'never'.` where ever `emailEditorRef.current.editor` is referenced. Any ideas of how to fix this?
<img width="732" alt="Screen Shot 2022-07-24 at 10 33 25 AM" src="https://user-images.githubusercontent.com/905178/180659154-7d020d5b-fd6b-465b-915e-fa63607a3c03.png">

**Comment by driaug** [comment]
I have simply TS ignored the error because it is functional code, just has no TS support. 

In theory, you could write your own explicit typing to fix the error but the complete lack of documentation makes it nearly impossible...

**Comment by akleshsakunia** [comment]
I tried adding `any` as reference type and it worked.
So with typescript support on the starter code in readme would look as below
```typescript
import React, { useRef } from "react";
import { render } from "react-dom";

import EmailEditor from "react-email-editor";

export default () => {
  const emailEditorRef = useRef<any>(null);

  const exportHtml = () => {
    emailEditorRef.current!.editor.exportHtml((data: any) => {
      const { design, html } = data;
      console.log("exportHtml", html);
    });
  };

  const onLoad = () => {
    // editor instance is created
    // you can load your template here;
    // const templateJson = {};
    // emailEditorRef.current.editor.loadDesign(templateJson);
  };

  const onReady = () => {
    // editor is ready
    console.log("onReady");
  };

  return (
    <div>
      <div>
        <button onClick={exportHtml}>Export HTML</button>
      </div>

      <EmailEditor ref={emailEditorRef} onLoad={onLoad} onReady={onReady} />
    </div>
  );
};
```

**Comment by sean-beard** [comment]
Try defining the ref like this:
```typescript
const emailEditorRef = useRef<InstanceType<typeof EmailEditor> | null>(null);
```

Then using the ref without accessing the `editor` property will give you intellisense:
![type-fix](https://user-images.githubusercontent.com/8262156/194434404-0d95cac1-75f5-49d4-91e3-1fb94133847c.gif)

**Comment by lucasbesen** [comment]
Please update to the latest version. We have types now.

@timsun28 I have updated the getting started example, you should use `onReady` instead of `onLoad`
