### ISSUE TITLE
Make Mixpanel Opt In

### ISSUE THREAD

**Issue by generalleger** [unlayer/react-email-editor#27]
Would you all consider making mixpanel opt-in.  Those of us needing to comply with GDPR need full control over what data about our users is sent to third parties.

**Comment by adeelraza** [comment]
@generalleger no user data, or any personally identifiable information is passed to mixpanel. It's just for event tracking on anonymous editor usage.

**Comment by generalleger** [comment]
Just something to consider.  In a compliance environment, it is difficult for anyone to conclude that no sensitive data is being sent to mix panel without constantly inspecting the traffic.  For users of your paid service, there is a contract/agreement which should outline what data is being sent, and if you are not in compliance with your contracts, then at least your clients have a legal basis for a defense.  For people who npm install the react package, there is no such agreement, so the onus of knowing what is being sent falls to the package user, and since you can change at any time what is sent to mix panel, there is a GDPR compliance quandary to consider. I think the cleanest way would be to somehow provide an option when loading the editor so that tracking libraries don't load.

Maybe an alternative is to create a GDPR statement somewhere in the repo indicating what data is being sent so that organizations can have that as documentation in the event there is an inquiry from a Supervisory Authority.

Again, just a consideration.  Thanks for the great library.

**Comment by adeelraza** [comment]
@generalleger mixpanel has been removed
