### ISSUE TITLE
Custom Tools Implementation Not Working

### ISSUE THREAD

**Issue by Tenurian** [unlayer/react-email-editor#29]
Hey so I'm trying to figure out how to implement a custom tool into the react component, and the link you provide takes me to the Unlayer documentation, which provides zero helpful documentation for this component. It assumes the user is using the CDN for Unlayer and has access to the `unlayer` global object, which makes all their documentation useless to me. I have the `react-email-editor` component set up in my project and working quite well, and I need to add several custom tools. I've been emailing back and forth with Unlayer Support trying to figure out how to add my own tool but the rep I talk to keeps going back to using the `unlayer` global object, and when I tried to patchwork a tool into the tools prop, nothing worked.

An example of how to properly use the tools prop would be amazing.

**Comment by adeelraza** [comment]
@Tenurian here's an example: https://github.com/unlayer/examples/tree/master/custom-tool-and-property-editor

You can clone it, and run `npm install` and `npm start`, then open it in your browser.

**Comment by Tenurian** [comment]
I saw this post while emailing support at email, and I'll tell you what I told him: We are using server-side rendering and don't have access to the global unlayer object. Do I need to go into our index file and add the embed script in order to get custom tools working? and follow up question: If I'm importing your package from NPM, but the unlayer script is using CDN, how am I going to have access to unlayer inside my component scripts?

**Comment by Tenurian** [comment]
Okay so I just got another email from unlayer support and I think i'm starting to get the picture now. Through the React component, any file I pass in will have the unlayer global object exposed, and inside that same file I pass in I can add my custom tools, if I'm understanding correctly.

**Comment by Tenurian** [comment]
Let me ask my original question another way: in all the examples you and your company keep sending me, you keep calling `unlayer.init()` on the index.html file. Since I'm using the react component, I don't have the same cdn link and therefore do not have `unlayer.init()` so how do I pass in the code I need into the react component?

**Comment by sparkbold** [comment]
https://editor.unlayer.com/embed.js kept getting pending from my side. Is there a CDN that we can use or an offline version that we can load from our server? Thank you.

**Comment by fnaquira** [comment]
> 
> 
> @Tenurian here's an example: https://github.com/unlayer/examples/tree/master/custom-tool-and-property-editor
> 
> You can clone it, and run `npm install` and `npm start`, then open it in your browser.

Link down

**Comment by Tenurian** [comment]
@sparkbold There is no "Offline" version of Unlayer unfortunately, as the actual plugin is an iFrame loading from a remote source. If your network is closed off from the internet, Unlayer won't work. Our team had to find another solution due to this.

**Comment by adeelraza** [comment]
@sparkbold @Tenurian we do have offline version and on-premise available in our Enterprise plans. Please contact our sales team for more information.

**Comment by Tenurian** [comment]
Apologies, I misspoke and @adeelraza is correct. The _free_ version doesn't allow for offline compatibility, which is why our team chose to pursue other options.

**Comment by Roucoz** [comment]
> Hey so I'm trying to figure out how to implement a custom tool into the react component, and the link you provide takes me to the Unlayer documentation, which provides zero helpful documentation for this component. It assumes the user is using the CDN for Unlayer and has access to the `unlayer` global object, which makes all their documentation useless to me. I have the `react-email-editor` component set up in my project and working quite well, and I need to add several custom tools. I've been emailing back and forth with Unlayer Support trying to figure out how to add my own tool but the rep I talk to keeps going back to using the `unlayer` global object, and when I tried to patchwork a tool into the tools prop, nothing worked.
> 
> An example of how to properly use the tools prop would be amazing.

@Tenurian 
Hello Tenurian. I am just using the Unlayer tool, and i am stuck in this error that you mention. I can see in your conversation history that you resolved how to resolve unlayer.init(..). I checked the git repo that someone send it to you and it does no exist.

Do you remember what did you do to resolve this issue?
Thank you in advance
