### ISSUE TITLE
Custom title Merge tags

### ISSUE THREAD

**Issue by bavachaucp0002** [unlayer/react-email-editor#299]
Can i change this text or custom UI for this
Thank alot!!!
<img width="592" alt="Screenshot 2023-02-09 at 15 48 44" src="https://user-images.githubusercontent.com/42066901/217762607-71e377dc-c0e0-4424-b4fe-4f7407808cf6.png">

**Comment by nickymalayba** [comment]
Same, any updates?

**Comment by PatilSarvesh** [comment]
Use this it will work
locale: "en-US",
            translations: {
                "en-US": {
                    "labels.merge_tags": "Custom Name",
                },
            },'
   
         
https://github.com/unlayer/translations/blob/master/en.json
