### ISSUE TITLE
move styled-components to peerDependencies

### ISSUE THREAD

**Issue by busstram** [unlayer/react-email-editor#30]
We're running 2 conflicting versions of styled-components, due to it being a hard dep. Could you move it to peerDependencies? You don't use any legacy APIs. You could opt for `2.x || 3.x` as well.

**Comment by aliogaili** [comment]
I'm having the same issue..

**Comment by aliogaili** [comment]
Yes that's what I did as well

**Comment by adeelraza** [comment]
@busstram this is fixed
