### ISSUE TITLE
Exit Code 1 when installing react-email-editor

### ISSUE THREAD

**Issue by sulmanazhar2** [unlayer/react-email-editor#306]
My deployment was working perfectly fine but today for some reason whenever I try to install dependency it then gives me an error
```
error C:\react\infaque\node_modules\react-email-editor: Command failed.
Exit code: 1
Command: cd demo && npm install
Arguments:
Directory: C:\react\infaque\node_modules\react-email-editor
Output:
The system cannot find the path specified.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I tried uninstalling node_modules, lock files, changed yarn version, tried different operating systems and tried installing dependencies in node_modules -> react-email-editor folder. But nothing is working.

**Comment by sahilkhaire** [comment]
This is with latest package version 1.7.0... i have downgraded to 1.6.3 and worked fine for now...

**Comment by bavicj** [comment]
Having same issue

**Comment by sulmanazhar2** [comment]
It wasn't related to the version because i tried many versions on different platforms and in the end it started working on its own. I might be wrong but I believe the issue was when the package was being fetched from the servers etc.
Anyway it's fixed now. Thank you
