### ISSUE TITLE
Unlayer Editor iframe lagging wierd issue

### ISSUE THREAD

**Issue by jay-softsages** [unlayer/react-email-editor#311]
Please take a look at this video -

https://user-images.githubusercontent.com/120706758/220582707-93384c0f-d96b-41de-926c-f92a6420300b.mp4

The iframe document head is constantly updating the style and script tag which is making the iframe very laggy and my website become unresponsive. I have embedded this in my React project and the weird thing is that if I run my react project locally then this issue is not occurring but only happens on the live build where it is deployed.

Any particular reason why this is happening? Please help.

**Comment by lucasbesen** [comment]
@jay-softsages I'm not able to reproduce it. Could you share a live version and your code?

**Comment by brunolemos** [comment]
Maybe you are making some design change in the wrong place? For example, do not call `unlayer.setBodyValues()` or something like that inside the `design:updated` callback, call it inside the `editor:ready`.

**Comment by jay-softsages** [comment]
@brunolemos @lucasbesen  Thanks for the reply.
I am not loading a design or any other callbacks multiple times.

I am just embedding the editor and loading the design if any, or else I show an empty editor. Please see my react code below -
```javascript
const loadDesign = useCallback(() => {
    if (emailEditorRef.current && props.draftJsonContent) {
      emailEditorRef.current.loadDesign(props.draftJsonContent);
    }
  }, [emailEditorRef]);
```
```javascript
<EmailEditor
      ref={emailEditorRef}
      onReady={() => loadDesign()}
      minHeight={800}
/>
```

Could this be a browser issue?

**Comment by brunolemos** [comment]
Hi @jay-softsages, what was the issue?
