### ISSUE TITLE
[TS] 'unlayer' was also declared here.

### ISSUE THREAD

**Issue by PavelTankovich** [unlayer/react-email-editor#334]
When running the tsc command, I am receiving an error that is breaking my project tests.

Steps to reproduce:

Install "react-email-editor": "^1.7.8"
Run the tsc command in the terminal.
![image](https://user-images.githubusercontent.com/34751890/232745844-6ae6a972-ee35-4b23-ab95-7f55b3ac202c.png)

**Comment by brunolemos** [comment]
Unlayer's script injects a global variable called `unlayer`. So it's better that you use a  different name for your variable to avoid conflicts.

**Comment by PavelTankovich** [comment]
@brunolemos  That's the problem that I don't use such a variable. The problem is in your library. Have you tried reproducing it?

**Comment by brunolemos** [comment]
Based on the error screenshot, it seems that the cause is that both `src` and `dist` are published to npm. Probably only `dist` should be published to npm.

**Comment by brunolemos** [comment]
@PavelTankovich please try `brunolemos-react-email-editor@2.0.3` and let me know if it works well for you.
