### ISSUE TITLE
onReady | call outside from editor component

### ISSUE THREAD

**Issue by MwSpaceLLC** [unlayer/react-email-editor#335]
Hi there

Today i want share with u little bug (tink)

If we use in same page input or another dom changes, the onReady function by editor, will be re-call.

Ex, in below, if u load dom, u can see 1 log, but if u type in input, u can see another log, same called from onReady..

![image](https://user-images.githubusercontent.com/29952045/233784201-610edcfb-567d-4d37-8553-a7ac9a3b69a3.png)

Why? U can test input onChange: https://codesandbox.io/s/blue-dust-3kzxtg?file=/src/App.js

**Comment by xinghengwang** [comment]
have same issue. onReady suppose to be their hook for us to initiate the editor.  it is triggered when anything else on the page is shown and unshown, and thus resets everything. So frastrating with their support. and I am paying customer.

**Comment by Arsenalist** [comment]
I'm having this issue as well. onReady is called when I make an HTTP call inside onReady. This makes no sense.
