### ISSUE TITLE
[TS] 'unlayer' was also declared here.

### ISSUE THREAD

**Issue by PavelTankovich** [unlayer/react-email-editor#343]
[ #334 ]  My problem was just closed without trying to reproduce it, so I'm opening it up again
When running the tsc command, I am receiving an error that is breaking my project tests.

Steps to reproduce:

Install "react-email-editor": "^1.7.8"
Run the tsc command in the terminal.
![image](https://github.com/unlayer/react-email-editor/assets/34751890/0d9a9142-248a-4930-bdfa-a0cd3ad30f85)

**Comment by brunolemos** [comment]
Let's use the original issue instead
