### ISSUE TITLE
x.addEventListener is not a function

### ISSUE THREAD

**Issue by hasanugr** [unlayer/react-email-editor#357]
Hi there,

We are getting `Uncaught TypeError: x.addEventListener is not a function` in version 1.7.9. This problem started with version 1.7.9.
I solved this problem in my own project by fixing the version to 1.7.8.

A permanent solution is needed for this problem.

<img width="620" alt="Screenshot 2023-09-04 at 19 29 42" src="https://github.com/unlayer/react-email-editor/assets/18167158/78784c43-23ef-4a6f-a2b5-e3dc60bba74b">

**Comment by brunolemos** [comment]
We cannot reproduce this issue. Are you calling `addEventListener` yourself in your code? If so, make sure to call it as `emailEditorRef.current.editor.addEventListener(...)` and not `emailEditorRef.current.addEventListener(...)`.
