### ISSUE TITLE
How can I add callback to form tool?

### ISSUE THREAD

**Issue by permlap-phola** [unlayer/react-email-editor#370]
As the title says, is there anyway that I can add callback function to form tool?
Accroding to https://docs.unlayer.com/docs/form-tool#submit-actions you need to pass tools properties to the react-email-editor, however it seem react-email-editor doesn't provide tools properties anymore.
So, how can I achieve that?

**Comment by brunolemos** [comment]
Use the `options` prop to pass the fields you see in the docs, like the `tools` one and others. 

```
options={{ tools: { ... } }}
```
