### ISSUE TITLE
Too much memory usage recently

### ISSUE THREAD

**Issue by eduschneiders** [unlayer/react-email-editor#373]
Has there been any recent major updates?
Each browser tab (regardless of the browser) is reaching 300MB usage, and it wasn't like this before.
Employees in my company with 8GB RAM computers are reporting browser tabs crashing(only the ones with the unlayer editor).

Is anyone experiencing the same problem?

**Comment by brunolemos** [comment]
@eduschneiders can you share a link we can access to reproduce the issue?
