### ISSUE TITLE
Error while trying to registerCallback

### ISSUE THREAD

**Issue by M0hammedImran** [unlayer/react-email-editor#374]
When I try to `registerCallback` for `selectImage` I see the following error on the UI.
![Screenshot from 2023-11-23 13-11-51](https://github.com/unlayer/react-email-editor/assets/52968617/9f4fa0c1-7483-4700-9bd7-02abdf4832e3)

This is the code used to `registerCallback`
```js
editor.registerCallback("selectImage", (file, done) => {
  this.setState({ openImageSelectionModal: true });
  this.done = done;
});
```

And when image is selected, I call `done` callback
```js
this.done({ url: data });
```

After calling done things seem to work as usual.

**Comment by brunolemos** [comment]
Thanks for reporting @M0hammedImran. While that is not fixed, you can use this workaround:

```js
unlayer.registerCallback("selectImage", async (file) => {
  const thiss = this;

  thiss.setState({ openImageSelectionModal: true });

  return new Promise((resolve) => {
    thiss.done = resolve;
  });
});
```

**Comment by M0hammedImran** [comment]
> Thanks for reporting @M0hammedImran. While that is not fixed, you can use this workaround:
> 
> ```js
> unlayer.registerCallback("selectImage", async (file) => {
>   const thiss = this;
> 
>   return new Promise((resolve) => {
>     thiss.done = resolve;
>   });
> });
> ```

Thanks @brunolemos, this worked for me.

**Comment by brunolemos** [comment]
@M0hammedImran we have released a fix. please revert back to your original code instead of the workaround. thanks!
