### ISSUE TITLE
customCSS & customJS props restricted to a specific projectId

### ISSUE THREAD

**Issue by joejemmely** [unlayer/react-email-editor#38]
I tried to use the customCSS & customJS props based on the examples in the playground, but it is only working with project ID 1071.

Is it possible to open these features to other projects as well?

**Comment by adeelraza** [comment]
@joejemmely custom JS is a premium feature. Please check our pricing plans here: https://unlayer.com/pricing

**Comment by lidrissi** [comment]
> @joejemmely custom JS is a premium feature. Please check our pricing plans here: https://unlayer.com/pricing

So we can not create a custom tools in a free plan ?
