### ISSUE TITLE
image export failing

### ISSUE THREAD

**Issue by geikobogdan** [unlayer/react-email-editor#389]
I have my apiKey and project id, but when I try to execute `imageExport` func I received 401.  Attached screenshots with request details (request headers/url, payload).  Code:

```
import { Editor } from "react-email-editor/dist/types"

const EmailEditorNoSSR = dynamic(() => import("react-email-editor").then((mod) => mod.default), { ssr: false })


const projectId = 11111 //your project id


export const EmailBuilderModal: FC<EmailBuilderProps> = ({ open, setOpen }) => {
  const emailEditorRef = useRef<EditorRef | null>(null)

  const onReady = (editor: Editor | null) => {
    if (editor) {
      emailEditorRef.current = {
        editor: editor,
        exportHtml: editor.exportHtml.bind(editor),
      }
      setIsLoading(true)
    }
  }


  const saveImage = async () => {
    if (emailEditorRef.current && emailEditorRef.current.editor) {
      emailEditorRef.current.editor.exportImage(({ design }) => {
        console.log(design, "design")
      }) // 401 error
    } 
  }

  return (
          <EmailEditorNoSSR
              projectId={projectId}
              ref={emailEditorRef}
              onReady={onReady}
            />
         )
})
```

<img width="1004" alt="Screenshot 2024-03-21 at 13 11 47" src="https://github.com/unlayer/react-email-editor/assets/56224886/f541d6d1-5d02-48a1-a758-4ea0dc129989">
<img width="1496" alt="Screenshot 2024-03-21 at 13 13 18" src="https://github.com/unlayer/react-email-editor/assets/56224886/f151bcda-211c-4f6a-af17-57a94a40ca8e">
<img width="1512" alt="Screenshot 2024-03-21 at 13 13 32" src="https://github.com/unlayer/react-email-editor/assets/56224886/a115d8a1-99ea-4b1c-b2c6-707137860921">

**Comment by abhishekti7** [comment]
@geikobogdan any updates on this? I am also facing this issue

**Comment by geikobogdan** [comment]
@abhishekti7 we used wrong plan, so it's already resolved

**Comment by abhishekti7** [comment]
@geikobogdan is this a premium feature? Are you using your own handler for saving images?
