### ISSUE TITLE
Editor is reloading when press ENTER in  the link inputs

### ISSUE THREAD

**Issue by shkhalid** [unlayer/react-email-editor#398]
This can be also reproduced on https://react-email-editor-demo.netlify.app/

https://github.com/unlayer/react-email-editor/assets/8138036/a67d0ec0-e28a-4a8e-9075-818730067edd

**Comment by ivoIturrieta** [comment]
Thanks for bringing this up. I checked on my end and seems to be an issue after we released the redesign. We'll take a look at it

**Comment by willianjusten** [comment]
+1 impacted by this issue 😅

**Comment by brunolemos** [comment]
This will be fixed in the next editor version.

**Comment by willianjusten** [comment]
Any deadline for that? =D

**Comment by brunolemos** [comment]
The fix is available on editor `version: 'latest'`, starting at `1.47.0`.
