### ISSUE TITLE
Unlayer Types not correct for the newer version

### ISSUE THREAD

**Issue by willianjusten** [unlayer/react-email-editor#399]
Hey guys, I just saw you updated Unlayer to it's new version, but I also noticed that the `unlayer-types` package is not updated yet.

If I try to use the `classic_light` version, my TS fails because it does not have this type there. I saw the [package](https://www.npmjs.com/package/unlayer-types) and indeed, it's not there.

<img width="932" alt="image" src="https://github.com/unlayer/react-email-editor/assets/3991845/cc92801b-9af5-402b-a1db-3f3c7dd4e3f7">

Also, is there a list of latest versions of the Unlayer editor so I can lock correctly? I can't find anywhere...

**Comment by brunolemos** [comment]
We have an internal fix for that! It's not available yet. You can make ts ignore that line for now.

We don't have a list of versions, but I believe that is something we will be doing from now on and they'll be available in the Docs Changelog: https://docs.unlayer.com/changelog

**Comment by willianjusten** [comment]
Would you mind telling me the latest version prior this theme update?

**Comment by brunolemos** [comment]
@willianjusten `1.5.75` 

What did the new version break for you?

**Comment by willianjusten** [comment]
Ah, so it's the same as in the Docs you sent me, perfect.
It broke most of the Custom CSS stuff because some classes changed and there are also some new visuals. Nothing big and we're already with a task to fix that, but I didn't want to have anything broken (even thought is not in prod yet).

**Comment by brunolemos** [comment]
@willianjusten cool! thanks for letting me know

show us the customization later if you can :)

**Comment by willianjusten** [comment]
Sure, I'll let you know as soon as we release this new feature. It will come in the next few months =)

**Comment by brunolemos** [comment]
We released a new `unlayer-types` version with the fix! Thanks.
