### ISSUE TITLE
Template Color issue for #ccc

### ISSUE THREAD

**Issue by nathanjo** [unlayer/react-email-editor#402]
This is even exist in your demo! When selecting #ccc under the Template Color, it gives your #CC0C00
![Screenshot 2024-05-14 at 22 34 24](https://github.com/unlayer/react-email-editor/assets/932018/191e8c63-be89-4989-a254-e997b14760e1)

**Comment by ivoIturrieta** [comment]
Thanks for bringing this up. It does seem to be an issue. We'll take a look at it
