### ISSUE TITLE
Custom Media Library is not working anymore?

### ISSUE THREAD

**Issue by WardenCommander** [unlayer/react-email-editor#429]
It is not possible to trigger Custom Media Library?
following this docs: https://examples.unlayer.com/media/custom-media-library/

custom media library is not triggering, and it ask for standard image upload

and acording to this documentation: https://docs.unlayer.com/docs/custom-image-library
it is not "Premium Feature"

but on: https://billing.unlayer.com/
its: "Enterprise Custom"

**Comment by AshishTondon** [comment]
I am getting same error. Please help

**Comment by omerzahidbajwa** [comment]
Hi,

Please let me know if you pass in a "projectId" during initialization. Unlayer has just rolled out new billing plans, and many features are paid. If you are an old user and have an old projectId available, you can still utilize the old "Free (Legacy)" plan feature sets.

Pass in the projectId within your editor, and make sure to add your live domain to the "Allowed Domains" list which you can find under project->settings->deployment.

Let me know if this works

**Comment by Keshavdulal** [comment]
Yeah seems like I am bit late to the party #427
