### ISSUE TITLE
Component calls home

### ISSUE THREAD

**Issue by DigitalFlow** [unlayer/react-email-editor#56]
Hey there,

I really like the editor, so first off thanks for publishing it.

What I'm wondering about however: When loading the editor sends a GET request to one of your servers, passing the current domain as parameter, like the following: `https://adminapi.unlayer.com/v1/editor/0?domain=yourdomain.com`.

Could you tell which other data you send to your servers?
In addition to that, as your editor is being loaded as iframe, I think people might feel a little bit more secure if you used the sandbox property of iframes.

Thanks in advance.

Kind Regards,
Florian

Edit: Just saw that several events also send requests with the full refferer url:
URL: `https://adminapi.unlayer.com/v1/editor/0/events`
Payload: `{"type":"editorReady","referrer":"http://domain.com/path/emaileditor.html?pagemode=iframe"}`
Examples for these events are the editorReady event on load and the exportHtml function for getting the editor's current state.

I'm not really happy about this, is this solely for telemetry?

**Comment by adeelraza** [comment]
@DigitalFlow these events are sent to Unlayer servers to track usage and make sure our premium services are not enabled on domains that are not whitelisted for those features. If you are not using a premium license, this wouldn't really matter.

**Comment by DigitalFlow** [comment]
@adeelraza 
Alright, thanks for sharing that information.

I hope that you'll have success with your business model, but what is going to happen, if you for any reason decide to discontinue this editor?
Since it is a wrapper component, will it die immediately? Or would you be going to publish the whole component in here?

I'd like to use it in a few places, but if there's the danger that it might stop working immediately at some point, that would be a great danger.

Kind Regards,
Florian

**Comment by adeelraza** [comment]
@DigitalFlow In the unlikely event that we discontinue the editor, we'll make it open source.

**Comment by DigitalFlow** [comment]
@adeelraza
That's great to hear, thanks a lot.

Just found your example templates at emailmonster.io, really great stuff, again thanks for providing it.

**Comment by sparkbold** [comment]
I know this issue has been closed but I wonder if we still can use your app without calling home. Our corp network block adminapi call. And now the app just kept spinning without loading anything. Thank you.

**Comment by murcoder** [comment]
hi there!

First of all, thanks for this great mail editor! We use it in our own react application, but sometimes the GET request to your servers results in a timeout: 

`GET https://adminapi.unlayer.com/v1/editor/0?domain=my-domain.com net::ERR_TIMED_OUT`

Is this a known problem or is there some solution for it?

**Comment by AlexCharlton93** [comment]
@sparkbold Hi, we are also currently experiencing this issue, I confirmed it by accessing the unlayer demo on my mobile data as opposed to the wiifi. Do you know how we can solve this? Or did you not find a solution.

Thanks in advance,
Alex

**Comment by dotkas** [comment]
Please, enable the ability to opt-out of usage tracking.
