### ISSUE TITLE
Convert HTML to JSON react-email-editor

### ISSUE THREAD

**Issue by vctqs1** [unlayer/react-email-editor#64]
I would like to creating form to edit data in HTML and raw HTML. But I am having problems how to convert HTML to JSON for email-editor?

Pls, help me

**Comment by adeelraza** [comment]
We only do one-way conversion from JSON to HTML.

**Comment by gjphilander** [comment]
I decided to tackle this issue and made good progress so far. My script can already convert 50% of unlayer html templates to unlayer json and I can successfully load it in the editor. Will see if I'm successful. I would guess that my script would at least convert the html 90%, but 100% is not improbable. As soon as I finish this project, I would like to convert any html template to unlayer.
