### ISSUE TITLE
Import HTML generated outside Unlayer

### ISSUE THREAD

**Issue by rgcarrasqueira** [unlayer/react-email-editor#66]
Hello! Is it possible to load inside unlayer legacy html created outside unlayer?

**Comment by adeelraza** [comment]
@rgcarrasqueira can you elaborate a little more?

**Comment by rgcarrasqueira** [comment]
I have email templates created in ckeditor, for example, I would like to know if is it possible to  import it to unlayer and edit it

**Comment by rgcarrasqueira** [comment]
Any news?

**Comment by adeelraza** [comment]
@rgcarrasqueira that is not possible. Our templates are only coded in JSON.

**Comment by rgcarrasqueira** [comment]
Can you share the standard, so we can create an app to convert it to json?

**Comment by talvbansal** [comment]
@rgcarrasqueira did you find out any more about this? or come up with an alternative work around?

**Comment by rgcarrasqueira** [comment]
No

**Comment by jeroenv** [comment]
Please take a look at https://docs.unlayer.com/docs/legacy-templates

**Comment by danbars** [comment]
If someone reaches here looking for a solution - I ended up creating a shell template with just one html block inside. 
Then I place my legacy html into that block, and load the template into unlayer.
in my case, the legacy HTMLs that I had were partial, meaning `<div>`, and not `<html>`
