### ISSUE TITLE
Cannot read property 'dom' of null

### ISSUE THREAD

**Issue by uplankita** [unlayer/react-email-editor#67]
On the development environment, it worked perfectly for me. While on the production environment I get this error. This does not occur everytime I use the editor but breaks sometimes, I was not able to observe any pattern in the occurence.

Kindly help with the causes of this error.

![image001](https://user-images.githubusercontent.com/41364044/55779173-62d82b00-5ac2-11e9-9200-952a10a8f825.jpg)

**Comment by tbnnrdt** [comment]
We are having the same issue here... Every time i click on a row or want to switch from one to another.

[Enregistrement de l’écran 2019-04-09 à 18.36.25.zip](https://github.com/unlayer/react-email-editor/files/3060063/Enregistrement.de.l.ecran.2019-04-09.a.18.36.25.zip)

![image](https://user-images.githubusercontent.com/9197185/55817743-7650b980-5af5-11e9-8a27-dd7f5c90fb49.png)

**Comment by adeelraza** [comment]
We have deployed a potential fix for this. Can you clear cache and try again?

**Comment by PucktheOrphan** [comment]
Appears resolved for our users (Uplankita team) after brief testing - not tested extensively yet though.

**Comment by uplankita** [comment]
@adeelraza Thanks! Seems to work right now so closing the issue, will be monitoring for any future occurence.
