### ISSUE TITLE
Reset editor

### ISSUE THREAD

**Issue by hfllr** [unlayer/react-email-editor#69]
Hello, is it somehow possible to reset/clear the content of the editor?

I tried saving the initial design object as a state and calling loadDesign(initialDesign) function but that just returned a blank page without the drag menu.

**Comment by adeelraza** [comment]
Your approach is correct. You have to use `loadDesign` and that will reset the state to whichever design you loaded.

**Comment by rr999888tw** [comment]
I encounter the error when I want to save the state for later usage in Componentdidmount

Here's what I did:
![image](https://user-images.githubusercontent.com/36822122/57596926-bc2ef080-757f-11e9-8908-f13fc46c2040.png)

Error message:
![image](https://user-images.githubusercontent.com/36822122/57596861-6e19ed00-757f-11e9-8b09-db6e0605dda8.png)

Any suggestion? Thanks in advance

**Comment by lidrissi** [comment]
try:
```
let editor = this.myRef.current || unlayer;
editor.saveDesign(json => .....
```

**Comment by hfllr** [comment]
For anyone encountering the same Problem as I did:

I solved the issue by saving the design as a state inside the editors "onDesignLoad" prop.
This way the editor has its elements already loaded and doesn't just return a blank page.
The only thing you need to be aware of is that the initialDesign state will get overwritten each time you'll load a new design. Just put a condition in front asking whether the initialDesign state is null in order to prevent this.
Now you can load an empty editor whenever needed.
