### ISSUE TITLE
OnLoad function call

### ISSUE THREAD

**Issue by Mabloq** [unlayer/react-email-editor#7]
Hey guys, Im unable to load JSON design via onLoad prop. However, I am able to load JSON manually using the same function called by the onLoad prop by pressing the load button once the editor is loaded. Below is my code an error message.
Im loading in the JSON via redux but I make sure the template json data is defined before rendering EmailEditor.

```
class Template extends Component {
  componentDidMount () {
    Promise.resolve (this.props.getTemplate ('emaily'));
  }
  loadDesign = () => {
    this.editor.loadDesign (this.props.template);
  }
  render () {
    return (
         // manual load button
        <button onClick={() => this.loadDesign ()} className="btn right">
            load
        </button>
        <EmailEditor
          onLoad={() => this.loadDesign()}
          //or
          //onLoad={this.loadDesign}}
          ref={editor => (this.editor = editor)}
        />
      </div>
    );
  }
}

function mapStateToProps (state) {
  return {template: state.template.currentTemplate};
}
export default connect (mapStateToProps, actions) (TemplateRF);

```

**Error message if .....onLoad={this.loadDesign}**
Uncaught (in promise) Error: Minified

**Error message if .....onLoad={() => this.loadDesign()**
Uncaught TypeError: Cannot read property 'get' of undefined
    at editor.js:2
    at l.configureFinalMapState (editor.js:2)
    at l.computeStateProps (editor.js:2)
    at l.updateStatePropsIfNeeded (editor.js:2)
    at l.render (editor.js:2)
    at d._renderValidatedComponentWithoutOwnerOrContext (editor.js:2)

**Comment by Mabloq** [comment]
I got it working so that unresolved promises aren't an issue, but the ref defined in the EmailEditor component will often times return undefined untill I reload the page again, a clue!

Upon checking the network requests I see that the adminApi.unlayer/v1 network request sometimes doesn't fire. In fact it only doesn't fire when I navigate to the page via a ReactRouter Link Component. Navigating to the page by typing the link out manually works 100%.

I will figure out how to make it so that navigating to the page via react-router Link component works and will provide an update.

**Comment by mersimoski** [comment]
For those struggling in 2023, no need for a timeout, just put the function that loads the design in `onReady` instead of `onLoad` since the ref will be loaded after everything is ready.

**Comment by udayan46** [comment]
@mersimoski ,  I need to load an html onReady function ,but getting these two errors everytime
1.editor.js:2 TypeError: Cannot read properties of undefined (reading 'values')
2.editor.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'values')

 below is my on ready function

const onReady = () => {
    let html_data = JSON.parse(
      JSON.stringify(props.templateData.resource[0].welcome_contenthtml)
    );
    const templateJson = { html_data };
    emailEditorRef.current.editor.loadDesign(templateJson);
  };
  ANY LUCK ?

**Comment by Anubhavgarg1910** [comment]
> @mersimoski , I need to load an html onReady function ,but getting these two errors everytime 1.editor.js:2 TypeError: Cannot read properties of undefined (reading 'values') 2.editor.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'values')
> 
> below is my on ready function
> 
> const onReady = () => { let html_data = JSON.parse( JSON.stringify(props.templateData.resource[0].welcome_contenthtml) ); const templateJson = { html_data }; emailEditorRef.current.editor.loadDesign(templateJson); }; ANY LUCK ?

Hey there, facing same issue. Did you get any solution for the same?
