### ISSUE TITLE
Editing Email Template Error: Uncaught (in promise) TypeError: Invalid template!

### ISSUE THREAD

**Issue by Clickview** [unlayer/react-email-editor#70]
Hello!

Receiving the error message `Uncaught (in promise) TypeError: Invalid template! Template should be a "string" but "object" was given as the first argument for mustache#render(template, view, partials)` when trying to edit an existing template.

This error started today and seems to be consistent.

**Comment by kevit-siddhant-prajapati** [comment]
I am also facing this issue

**Comment by axelphunter** [comment]
Suddenly facing this issue with valid template and no changes

**Comment by mydnic** [comment]
Did anyone find a solution ? Or the cause of the problem ?
