### ISSUE TITLE
Issue running editor.js  Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by mokkrb** [unlayer/react-email-editor#74]
I am using the react-package to load unlayer, which goes really well on my local env.
But as soon as I try on my production server, I keep running into this issue:

```
editor.js:2 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at Object.o (editor.js:2)
    at editor.js:2
    at Object.dispatch (editor.js:2)
    at g (editor.js:2)
    at editor.js:2
```

Expending the file, it looks like it comes from this part of the code:
```
function o(e) {
        var t = new URL(document.referrer);
        return Object(r.getRequest)("/".concat(e, "?domain=").concat(t.hostname))
    }
```

Has anyone bumped into this issue?

**Comment by mokkrb** [comment]
Just in case someone else bumps into this issue, I managed to find the root of it. I was simply blocking the referrer-policy on my end, which caused unlayer's script to fail.
Changing `referrer-policy` to `origin` (other values should be ok as well, depending on your needs) fixed the problem.

**Comment by shvhhhhh** [comment]
How to implement your solution can you send the code for that
