### ISSUE TITLE
Server side html render

### ISSUE THREAD

**Issue by munroe7** [unlayer/react-email-editor#81]
Not sure if I just missed it but, is there a way to render HTML via JSON without using the editor? I want to automate the emails that are created and currently store the JSON markdown in my database. When a user triggers an email, it should go to the database, grab the JSON markdown, convert to HTML, and then send off using an email package. Is this possible? Do I have to store the generated HTML in my database as well?

**Comment by lidrissi** [comment]
if you have a premium account check this end point:
https://docs.unlayer.com/reference#templatesidrender

**Comment by munroe7** [comment]
Is that the only solution? I'd prefer to store the email templates on my own server.

**Comment by lidrissi** [comment]
for me i store the exported html in the database

**Comment by munroe7** [comment]
Hmm, that's what I was originally doing. I was hoping that there was an easy server side solution so I could save on space in my database. Thanks for the input @lidrissi !
