### ISSUE TITLE
`loadDesign` documentation incorrect

### ISSUE THREAD

**Issue by olingern** [unlayer/react-email-editor#84]
From the docs:
> loadDesign - function(Object data) - Takes the design JSON and loads it in the editor

Should say:
> loadDesign - function(Object data) - Takes a design JSON **object** and loads it in the editor

The only way I was able to able to call `loadDesign` with JSON from `exportHtml` was to call `JSON.parse` on the exported design json.

Example

```javascript
  const handleChangeTemplates = (template) => {
    const parsed = JSON.parse(template.json)
    setEditorTemplateJson(parsed)
  }

  const setEditorTemplateJson = (templateJson) => {
    emailEditorRef.current.loadDesign(templateJson)
  }
```

```jsx
import EmailEditor from 'react-email-editor';

<EmailEditor ref={emailEditorRef} />
```

**Comment by Abhikumar98** [comment]
can you share the code for the same ?
I'm having some issues with it
