### ISSUE TITLE
Custom tool missing on load

### ISSUE THREAD

**Issue by niksib** [unlayer/react-email-editor#85]
When I trying to load my saved template vie load `this.editor.loadDesign(design)` all my custom tools show like "Missing", but when I clicked on this block it loading my tool.

Example - https://prnt.sc/os5o9i

**Comment by adeelraza** [comment]
@niksib are you using the JavaScript API to create the custom tool?

**Comment by niksib** [comment]
@adeelraza Yes with JavaScript API

**Comment by adeelraza** [comment]
@niksib can you clear your cache and try now? We have deployed a fix.

**Comment by niksib** [comment]
@adeelraza It works, thanks :)

**Comment by fnaquira** [comment]
Can you give an example of how to combine the Javascript API and the React Component?

**Comment by adeelraza** [comment]
@fnaquira https://playgrounds.unlayer.com/javascript/custom-tool-and-property-editor/
