### ISSUE TITLE
Changing the builder blocks

### ISSUE THREAD

**Issue by PersistentFK** [unlayer/react-email-editor#9]
Hi, thanks for the work!
I was wondering if there is any way to change the builder blocks code. I would like to make pdfs out with this drag and drop editor, so it needs some changes. My idea is that maybe it is possible if the builder blocks output different code.

Thanks!

Persistentfk

**Comment by adeelraza** [comment]
@PersistentFK this Github repo is solely for the email editor and email output. Please contact us at https://unlayer.com/contact/ to discuss PDF output.

**Comment by bilicio** [comment]
Hi, this pdf output work?
